export class User{
    korIme: string = ""
    lozinka: string = ""
    ime: string = ""
    prezime: string = ""
    pol: string = ""
    adresa: string = ""
    kontaktTelefon: string = ""
    gmail: string = ""
    profilnaSlika: string = ""
    brojKartice: string = ""
    tip: string = ""
    aktiviran: string = ""
    firma: string = ""
  }